Repository softeerbootcamp4th/Team3-Caecae-FE, pull requests merged in 2024-08, with the labels that each got.

#10 [Feat] 315 게임 컴포넌트의 레이아웃과 내부 게임 로직 구현
  Caecae/package.json
  Caecae/src/Job/Game315/Game315Work.tsx
  Caecae/src/Shared/assets/enterEventBtn.svg
  Caecae/src/Shared/assets/frontBackground.svg
  Caecae/src/Shared/assets/gameStartBtn.svg
  Caecae/src/Shared/assets/rearBackground.svg
  Caecae/src/Shared/assets/retryBtn.svg
  Caecae/src/Shared/assets/spacebarBtn.svg
  Caecae/src/Widget/Component/Game315/Game315.tsx
  Caecae/yarn.lock
Labels: enhancement

#19 [Feat] 레이싱 게임 랜딩페이지와 레이싱 게임 라우팅 연결
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/features/RacingGameLanding/EventIntro.tsx
  Caecae/src/features/RacingGameLanding/EventPeriod.tsx
  Caecae/src/index.tsx
Labels: feat

#39 [Fix] 다른 페이지로 라우팅 되었을 때 스크롤바가 맨위로 안가는 버그 수정
  Caecae/src/shared/Hyunouter/Router.tsx
Labels: Fix

#41 [Feat] 숨은그림찾기 및 레이싱 랜딩페이지에 공유 기능 구현
  Caecae/src/features/FindingGameLanding/LadingPageTitle.tsx
  Caecae/src/features/RacingGameLanding/EventIntro.tsx
Labels: Feat

#48 [Feat] 레이싱 게임 점수 백분위 확인 api 연결
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/stories/getRacingGameTopRate.tsx
Labels: Feat

#49 [Feat] 레이싱 게임에 백그라운드 오디오 구현
  Caecae/public/assets/audio/racingGamePlayingSound.wav
  Caecae/public/assets/audio/racingGameStopSound.wav
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/shared/Hyunxios/Hyunxios.tsx
  Caecae/src/utils/audioManipulate.tsx
Labels: Feat

#50 [Hotfix] Demo day에 있었던 날짜 체크 & x가 보이지 않던 오류 해결
  Caecae/src/components/FindingGame/FindingGame.tsx
  Caecae/src/features/FindingGameLanding/OpenEvent.tsx
Labels: Hotfix

#54 [Fix] 기존 hyundux - saga 좀 더 다양한 상황에 사용할 수 있도록 변경
  Caecae/src/components/FindingGame/FindingGame.tsx
  Caecae/src/jobs/FindingGame/FindingGameWork.tsx
  Caecae/src/shared/Hyundux-saga/Example/Example.tsx
  Caecae/src/shared/Hyundux-saga/Saga.tsx
  Caecae/src/shared/Hyundux-saga/Story.tsx
  Caecae/src/shared/Hyundux-saga/useSaga.tsx
  Caecae/src/stories/getFindGameIsAnswer.tsx
Labels: Fix

#59 [Feat] 레이싱 게임 기록 자랑하기 기능 구현
  Caecae/src/components/PhoneNumberOverlay/PhoneNumberOverlay.tsx
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/hooks/index.tsx
  Caecae/src/hooks/useDebounce.tsx
  Caecae/src/jobs/Overlay/OverlayWork.tsx
  Caecae/src/jobs/RacingGame/RacingGameWork.tsx
  Caecae/src/pages/Admin/AdminPage.tsx
  Caecae/src/pages/Admin/WinnerDTO.tsx
  Caecae/src/pages/FindingGame/FindingGamePage.tsx
  Caecae/src/pages/RacingGame/Enter/SelectCustom.tsx
  Caecae/src/pages/RacingGame/RacingGamePage.tsx
  Caecae/src/pages/RacingGameLanding/RacingGameLandingPage.tsx
  Caecae/src/stories/RacingGame/getRacingGameAvailable.tsx
  Caecae/src/stories/RacingGame/getRacingGameShortUrl.tsx
  Caecae/src/stories/RacingGame/getRacingGameTopRate.tsx
  Caecae/src/stories/getRacingGameOption.tsx
  Caecae/src/stories/getRacingGameTopRate.tsx
  Caecae/src/utils/audioManipulate.tsx
Labels: Feat

#55 [Hotfix] 레이싱 게임에 Saga 적용 후 리팩토링
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/hooks/useRacingGameAudio.tsx
  Caecae/src/jobs/RacingGame/RacingGameWork.tsx
  Caecae/src/pages/RacingGame/Enter/SelectCustom.tsx
  Caecae/src/stories/getRacingGameTopRate.tsx
  Caecae/src/utils/audioManipulate.tsx
Labels: Hotfix

#52 [Refactor] 레이싱 게임 오디오 로직을 useRacingGameAudio 커스텀 훅으로 리팩토링
  Caecae/src/hooks/useRacingGameAudio.tsx
Labels: Refactor

#66 [Hotfix] http에서 클립보드 api 사용 못해서 발생하는 버그 수정
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/features/FindingGameLanding/LadingPageTitle.tsx
  Caecae/src/features/RacingGameLanding/EventIntro.tsx
Labels: Hotfix

#69 [Hotfix] 레이싱 게임 스페이스바 이벤트리스너를 기존에 document에 걸었던 상태로 롤백
  Caecae/src/components/RacingGame/RacingGame.tsx
Labels: Hotfix

#70 [Deploy] version 0.1.1
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/features/FindingGameLanding/LadingPageTitle.tsx
  Caecae/src/features/RacingGameLanding/EventIntro.tsx
Labels: Deploy

#71 [Hotfix] 레이싱 게임 스페이스 컨트롤을 useKeyBoardControl 커스텀 훅으로 리팩토링 후 게임 플레이 시간을 랜덤으로 작동하게 수정
  Caecae/public/assets/audio/racingGamePlayingSound.wav
  Caecae/public/assets/eventPeriodBackground.svg
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/features/FindingGameLanding/OpenEvent.tsx
  Caecae/src/features/RacingGameLanding/EventPeriod.tsx
  Caecae/src/features/RacingGameLanding/HowToEvent.tsx
  Caecae/src/hooks/useKeyBoardControl.tsx
  Caecae/src/jobs/RacingGame/RacingGameWork.tsx
  Caecae/src/pages/RacingGame/Enter/SelectCustom.tsx
Labels: Hotfix

#72 [Hotfix] 폴더 구조 수정 및 이벤트 기간 설정에 따른 콘텐츠 텍스트 수정, 숨캐찾 게임내의 사진 에러 수정
  Caecae/src/components/FindingGame/FindingGame.tsx
  Caecae/src/components/common/PictureGameBoard/PictureGameBoard.tsx
  Caecae/src/features/EventInfoLanding/EventInfoTitle.tsx
  Caecae/src/features/FindingGameLanding/OpenEvent.tsx
  Caecae/src/jobs/FindingGame/FindingGameWork.tsx
  Caecae/src/pages/FindingGame/Enter/SuccessEnterContent.tsx
  Caecae/src/pages/RacingGame/Enter/SelectCustom.tsx
  Caecae/src/stories/FindingGame/getFindGameHint.tsx
  Caecae/src/stories/FindingGame/getFindGameIsAnswer.tsx
  Caecae/src/stories/FindingGame/getFindingGame.tsx
  Caecae/src/stories/FindingGame/getFindingGameStartTime.tsx
  Caecae/src/stories/RacingGame/getRacingGameOption.tsx
Labels: Hotfix

#73 [Hotfix] head 태그 내에 아이콘과 타이틀 수정
  Caecae/index.html
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/features/EventInfoLanding/DarkTeaserCasper.tsx
Labels: Hotfix

#63 [Feat & Test] 테스트 코드를 위한 hyundux-test 모듈 구현 및 일부 테스트
  Caecae/.eslintrc.cjs
  Caecae/__tests__/FindGameTest/FindGameTest.ts
  Caecae/jest.config.cjs
  Caecae/package-lock.json
  Caecae/package.json
  Caecae/src/components/FindingGame/FindingGame.tsx
  Caecae/src/components/RacingGame/RacingGame.tsx
  Caecae/src/index.tsx
  Caecae/src/jobs/FindingGame/FindingGameWork.tsx
  Caecae/src/pages/FindingGame/Enter/EnterContent.tsx
  Caecae/src/shared/Hyundux-saga-test/SagaTest.ts
  Caecae/src/shared/Hyundux-saga/Saga.tsx
  Caecae/src/shared/Hyundux-saga/index.tsx
  Caecae/src/shared/Hyundux-saga/useSaga.tsx
  Caecae/src/shared/Hyundux-test/Tester.tsx
  Caecae/src/shared/Hyundux/Actions.tsx
  Caecae/src/shared/Hyundux/Example_Counter/ConuntUI.tsx
  Caecae/src/shared/Hyundux/Example_Counter/CountDo.tsx
  Caecae/src/shared/Hyundux/Store.tsx
  Caecae/src/shared/Hyundux/index.tsx
  Caecae/tsconfig.app.json
  Caecae/tsconfig.json
  Caecae/yarn.lock
Labels: Feat, Test
